### ISSUE TITLE
Window resize APIs misleading

### ISSUE THREAD

**Issue by tyler-conrad** [ryanisaacg/quicksilver#412] opened 2018-12-06 01:49 UTC
Using the ResizeStrategy::Stretch whenever the window size is resized to less than the initially configured size drawing a rectangle with size = window.screen_size() does not fill the window.  The window.screen_size() reported from the println!() below does appear to be correct, the rectangle is just not filling the available space.

![resize](https://i.postimg.cc/MK0LYTN0/resize.png)

```rust
extern crate quicksilver;

use quicksilver::{
    Result,
    geom::{Vector, Rectangle},
    graphics::{
        Background::Col,
        Color,
        ResizeStrategy,
    },
    lifecycle::{Settings, State, Window, run},
};

struct ResizeTest;

impl State for ResizeTest {
    fn new() -> Result<ResizeTest> {
        Ok(ResizeTest)
    }

    fn draw(&mut self, window: &mut Window) -> Result<()> {
        window.clear(Color::BLACK);
        let size = window.screen_size();
        println!("{:#?}", size);
        window.draw(&Rectangle::new(Vector::ZERO, size), Col(Color::BLUE));
        Ok(())
    }
}


fn main() {
    let mut settings = Settings::default();
    settings.resize = ResizeStrategy::Stretch;
    run::<ResizeTest>("ResizeTest", Vector::new(512.0, 512.0), settings)
}
```
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.1 LTS
Release:	18.04
Codename:	bionic

rustc 1.30.1 (1433507eb 2018-11-07)
binary: rustc
commit-hash: 1433507eba7d1a114e4c6f27ae0e1a74f60f20de
commit-date: 2018-11-07
host: x86_64-unknown-linux-gnu
release: 1.30.1
LLVM version: 8.0

quicksilver = "0.3.2"

**Comment by ryanisaacg** [comment] 2018-12-08 19:45
I’ll try to reproduce and fix that this weekend.

**Comment by ryanisaacg** [comment] 2018-12-10 02:54
So this is actually a mental model mismatch between user expectations and what Quicksilver is doing.

The ResizeStrategy isn't the only thing that affects how content is scaled in Quicksilver: the window's current projection is also in effect. The goal of that system is that you simply pick your target resolution, draw at that resolution, and your resize strategy handles how the scaling works for other resolutions.

If you draw the rectangle at size 512 x 512, it will fill the screen as expected. If your goal is that the window does not do any projection, you can [set the Window's projection](https://docs.rs/quicksilver/0.3.2/quicksilver/lifecycle/struct.Window.html#method.set_view) to the screen size every frame in `draw`.

I'm going to leave this open for now because it wasn't even super clear to me what was happening, so the API might need to be reworked to be more clear.

**Comment by tyler-conrad** [comment] 2018-12-11 01:10
Adding a call to window.set_view() with the window size makes the Rectangle cover the entire window.  Thanks for looking in to this.

**Comment by ryanisaacg** [comment] 2019-07-17 02:22
I haven't figured out a more foolproof API for this, and it doesn't seem to come up super often. I'll close this for now, but I'll revisit it if there are more reports of problems.

**Closed by ryanisaacg** 2019-07-17 02:22 UTC
Labels: change-api-breaking, enhance-cleanup, enhance-feature, subsystem-graphics
