### ISSUE TITLE
Process didn't exit successfully

### ISSUE THREAD

**Issue by bachm** [ryanisaacg/quicksilver#453] opened 2019-01-23 13:29 UTC
I'm trying to run the example here https://github.com/ryanisaacg/quicksilver but get `error: process didn't exit successfully: `target\debug\galaxy-prototype.exe` (exit code: 3221225781)`.

- Environment: Windows 7
- Rust compiler version: stable-x86_64-pc-windows-msvc (default) rustc 1.32.0 (9fda7c223 2019-01-16)
- Quicksilver version: latest version

**Comment by ryanisaacg** [comment] 2019-01-23 14:30
Hi! Can you post what command you're running?

**Comment by bachm** [comment] 2019-01-23 15:15
Just `cargo run`

**Comment by ryanisaacg** [comment] 2019-01-23 15:58
What is the code you're trying to run? (Your link to the example is just a link to the repo main page)

**Comment by bachm** [comment] 2019-01-23 18:35
The example in the repo main page, `examples/draw-geometry.rs`

**Comment by ryanisaacg** [comment] 2019-01-23 20:45
Is there any backtrace available?

**Comment by bachm** [comment] 2019-01-23 21:40
Visual Studio Code was apparently suppressing an error message about missing XINPUT1_4.dll, which isn't available for Win 7 https://docs.microsoft.com/it-it/windows/desktop/xinput/xinput-versions

**Comment by ryanisaacg** [comment] 2019-03-11 13:40
So I've looked into this more, this is actually a problem with the gamepad library gilrs. You can choose to disable the gamepad feature for now; I believe they're working on a fix for this issue. Closed because it is caused by upstream.

**Closed by ryanisaacg** 2019-03-11 13:40 UTC
Labels: bug: needs repro
