### ISSUE TITLE
Pointer state location is always (0,0)

### ISSUE THREAD

**Issue by PvdBerg1998** [ryanisaacg/quicksilver#635] opened 2020-07-04 13:31 UTC
**Describe the bug**
Pointer state always contains (0,0) as the position.

**To Reproduce**
- Run webapp
- Debug print the pointer coordinates on PointerInput event

**Environment and versions:**
- Environment: Windows 10, Android 10 Firefox & Chrome
- Rust compiler version: nightly msvc
- Quicksilver verison: 0.4 alpha 5

**Comment by ryanisaacg** [comment] 2020-07-24 04:36
Hm, I can't reproduce this. When using the `08_input` example, I see the cursor position being updated on both web and desktop.

I think the mobile issue is possibly caused by rust-windowing/winit#1286?

**Comment by ryanisaacg** [comment] 2020-09-24 21:50
Closing, feel free to re-open with a reproducing example

**Closed by ryanisaacg** 2020-09-24 21:50 UTC
Labels: bug: needs repro, subsystem-input
