### ISSUE TITLE
WASM - image, font, and sound examples fail at runtime on `development` branch

### ISSUE THREAD

**Issue by beatgammit** [ryanisaacg/quicksilver#343] opened 2018-08-06 17:03 UTC
**Describe the bug**
I get "unreachable executed" on each example, and letting it run gives me that over and over.

I'm guessing loading resources is broken right now.

**To Reproduce**
1. mkdir static; ln -s ../examples static/examples
2. cargo +nightly web start --release --target=wasm32-unknown-unknown --example <example>
3. Open browser to localhost:8000
4. Open developer console, see error

**Expected behavior**
I expect the examples to work.

**Operating Environment (please complete the following information):**
- Arch Linux, tested with Chrome and Firefox
- Chrome 68.0.3440.75 and Firefox 61.0.1

**Versions (please fill out the following information)**
- rustc 1.30.0-nightly (73c78734b 2018-08-05)
- quicksilver latest development branch

**Additional context**
It looks like files are being downloaded, so resource loading *seems* to be working somewhat.

I don't know how to really debug stuff in WASM, but I *did* try switching all `unreachable!` lines to `panic!(...)` and the error remained the same, so it seems like the error is coming from some dependency.

**Comment by ryanisaacg** [comment] 2018-08-06 23:51
Try updating to the latest development branch and re-running (I expect you'll still get errors, but at least they should be logged!)

**Comment by beatgammit** [comment] 2018-08-07 02:02
Awesome, I'll give this a try tonight. I didn't know about the `console!` macro (new to Rust WASM).

**Comment by ryanisaacg** [comment] 2018-08-07 14:28
So in your PR you said this doesn't fully resolve your issues, what is the behavior now?

**Comment by beatgammit** [comment] 2018-08-07 14:40
Images don't render, but it no longer errors. I'm not sure what's causing it to not render, but I'm guessing we're sending something unexpected to the JavaScript shim.

I plan to take a look at it tonight, and if I can't figure it out, I'll try to get better debug info.

**Comment by beatgammit** [comment] 2018-08-07 16:52
Or if you could point me to where texImage2D is being called, that would also be awesome.

I'm guessing `load_image` in `bridge.js` somehow gets called from `load_image` in `file.rs`, but that's not really clear. I just don't really understand the linkage between JS and Rust I guess.

My guess is that it's in `rust_str_to_js` (probably a similar fix as in my PR), but by the time I figured out the Rust side of things, I didn't have much more time to work on it. I *think* I have a good handle on how to proceed, so I *should* have another patch this evening.

**Comment by ryanisaacg** [comment] 2018-08-07 16:54
Just a point of clarification: `bridge.js` is not used at all in the latest `development` branch. It's a legacy method of binding Rust to JS, and has been replaced by stdweb. So any JS code is either through the `stdweb` API or through a `js!` macro.

**Comment by beatgammit** [comment] 2018-08-07 20:50
Ah, nice. I'm guessing it doesn't support `vec<u8>` and wants a `TypedArray<u8>` or something. That'll save me a bit of frustration later :)

**Comment by beatgammit** [comment] 2018-08-08 04:42
Huh, I guess I don't really know what I'm doing now. I'm getting a black box instead of the image, and the only hint I get is the warnings. However, it's calling the draw functions quite a bit, yet I only get the warnings once, so I'm guessing it's something else.

My current guess is that something is amiss in the shaders. It's been a while since I did shaders, so I'll probably come back to this later once I've had time to read and feel a bit more comfortable with them. I feel like it's something simple, and it seems like the data is all in the right place.

Any insight you could give would be helpful. :)

**Comment by ryanisaacg** [comment] 2018-08-08 12:47
Sorry, I did work on this last night but am just now updating with what I learned.

Image loading is fixed, and I verified the correct image data is being gathered. However, there is a bug in the calls to the texture generation functions (specifically `texImage2D` and `generateMipmaps`) that is causing them to return `GL_INVALID_ENUM` as an error code. This is... unexpected, to say the least, as that code hasn't changed for quite a while but is no longer in a working state. Issue #348 has been opened to address this. 

Sound is a completely different problem; to be honest, I don't put much priority on sound and rarely test the sound example. It should be much easier to fix because it's basic JS / Rust communication issues. Issue #349 has been opened to address this.

Thanks for your patience as we fix these bugs, developing 0.3 has been a bit tumultuous with lots of breaking changes and I've been a bit negligent with testing all the examples when a change could impact them. I'm going to close this in favor of #348 and #349, which are the underlying issues that are still causing the examples to fail.

**Closed by ryanisaacg** 2018-08-08 12:47 UTC
Labels: bug: needs repro, platform-wasm

**Comment by ryanisaacg** [comment] 2018-08-09 12:57
I've got good news: #348 should be fixed, so feel free to test out fonts and textures; I'm hoping to be able to tackle sound bindings tonight.

**Comment by beatgammit** [comment] 2018-08-09 19:46
Holy crap you're fast :)

I'll test it out, and perhaps tackle one or two of the blockers for 0.3.

**Comment by ryanisaacg** [comment] 2018-08-09 20:29
To be honest fixing it that fast was mostly luck, because I hit on the cause of the underlying OpenGL issue fairly quickly. Weird OpenGL errors are almost enough to get me to scrap all my GL code and switch to Vulkan, but I doubt we'll see Vulkan support on Web so there's no reason to add that much complexity.

I'd really appreciate it if you took on one of the 0.3 issues! Just a heads up that I do have some WIP code for most of the issues (everything that isn't high-priority tends to be in a state of 30% completed until I get around to actually finishing it.) I'll try to get that all pushed up before this weekend, so you can fork off a feature branch if you want to finish something I've started.

**Comment by beatgammit** [comment] 2018-08-09 21:33
Sweet, I think I'll have some time this weekend. I'd like to see a 0.3 release sometime soon :)

**Comment by ryanisaacg** [comment] 2018-08-09 21:35
Ludum dare being this weekend is sort of a double-edged sword: it pushed me to get all the big flagship 0.3 features done, but also some bugs slipped through the cracks and I won't have time to finish up the last few blockers and make sure everything is ready to ship until next weekend probably.
