### ISSUE TITLE
wasm32-unknown-unknown compilation error

### ISSUE THREAD

**Issue by thallada** [ryanisaacg/quicksilver#251] opened 2018-06-16 23:42 UTC
I can't compile this library for wasm32. I followed the instructions in the README but got this error:

```
$ cargo +nightly build --target wasm32-unknown-unknown --release
   Compiling rand v0.5.1
   Compiling typenum v1.10.0
error[E0433]: failed to resolve. Use of undeclared type or module `imp`
   --> /home/thallada/.cargo/registry/src/github.com-1ecc6299db9ec823/rand-0.5.1/src/rngs/os.rs:118:18
    |
118 | pub struct OsRng(imp::OsRng);
    |                  ^^^ Use of undeclared type or module `imp`

error[E0433]: failed to resolve. Use of undeclared type or module `imp`
   --> /home/thallada/.cargo/registry/src/github.com-1ecc6299db9ec823/rand-0.5.1/src/rngs/os.rs:129:9
    |
129 |         imp::OsRng::new().map(OsRng)
    |         ^^^ Use of undeclared type or module `imp`

   Compiling matrixmultiply v0.1.14
error: aborting due to 2 previous errors

For more information about this error, try `rustc --explain E0433`.
error: Could not compile `rand`.
warning: build failed, waiting for other jobs to finish...
error: build failed
```
I'm using the latest nightly:
```
$ rustup show
Default host: x86_64-unknown-linux-gnu

installed toolchains
--------------------

stable-x86_64-unknown-linux-gnu
nightly-x86_64-unknown-linux-gnu (default)

installed targets for active toolchain
--------------------------------------

asmjs-unknown-emscripten
wasm32-unknown-emscripten
wasm32-unknown-unknown
x86_64-unknown-linux-gnu

active toolchain
----------------

nightly-x86_64-unknown-linux-gnu (default)
rustc 1.28.0-nightly (967c1f3be 2018-06-15)
```

Any idea how I could get this to compile?

**Comment by ryanisaacg** [comment] 2018-06-17 13:47
Sorry about that, there's currently a known issue with our use of the `rand` crate. Once I finish stdweb support #233, this will be fixed and you shouldn't have this issue. Sorry about that!

**Comment by ryanisaacg** [comment] 2018-06-18 21:48
@thallada stdweb support is all merged! Check out the readme for the new building instructions and let me know if there are any more issues.

**Comment by ryanisaacg** [comment] 2018-06-22 11:50
I'm going to close this because I was able to repro this issue and it should be fixed, let me know if it's still a problem and I'll reopen!

**Closed by ryanisaacg** 2018-06-22 11:50 UTC

**Comment by thallada** [comment] 2018-06-27 14:46
Hi @ryanisaacg I was offline for a bit and couldn't test this. I updated my `Cargo.toml` to include your changes:

```toml
quicksilver = { git = "https://github.com/ryanisaacg/quicksilver.git", branch = "development" }
```

And then I rebuilt with:

```bash
cargo +nightly build --target wasm32-unknown-unknown --release
```

But, I'm now getting this error:

```
error[E0432]: unresolved import `stdweb::web::event::GamepadConnectedEvent`
  --> /home/thallada/.cargo/git/checkouts/quicksilver-e70747fe04cf6e99/9d60f7f/src/state.rs:18:59
   |
18 |             event::{BlurEvent, ConcreteEvent, FocusEvent, GamepadConnectedEvent,
   |                                                           ^^^^^^^^^^^^^^^^^^^^^ no `GamepadConnectedEvent` in `web::event`
error[E0432]: unresolved import `stdweb::web::event::GamepadDisconnectedEvent`
  --> /home/thallada/.cargo/git/checkouts/quicksilver-e70747fe04cf6e99/9d60f7f/src/state.rs:19:17
   |
19 |                 GamepadDisconnectedEvent, IKeyboardEvent, IMouseEvent, IGamepadEvent,
   |                 ^^^^^^^^^^^^^^^^^^^^^^^^ no `GamepadDisconnectedEvent` in `web::event`
error[E0432]: unresolved import `stdweb::web::event::IGamepadEvent`
  --> /home/thallada/.cargo/git/checkouts/quicksilver-e70747fe04cf6e99/9d60f7f/src/state.rs:19:72
   |
19 |                 GamepadDisconnectedEvent, IKeyboardEvent, IMouseEvent, IGamepadEvent,
   |                                                                        ^^^^^^^^^^^^^ no `IGamepadEvent` in `web::event`
error[E0432]: unresolved import `stdweb::web::Gamepad`
 --> /home/thallada/.cargo/git/checkouts/quicksilver-e70747fe04cf6e99/9d60f7f/src/input/gamepad.rs:8:5
  |
8 | use stdweb::web::Gamepad as WebGamepad;
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ no `Gamepad` in `web`
error: aborting due to 4 previous errors
For more information about this error, try `rustc --explain E0432`.
error: Could not compile `quicksilver`.
```

I also tried with this in my `Cargo.toml` too, but no dice, same error:
```toml
stdweb = { git = "https://github.com/koute/stdweb.git" }
```

I see the [Gamepad stuff](https://github.com/koute/stdweb/blob/8c2d4998b2f80a6a3698a8606b034c451d6c919e/src/webapi/events/gamepad.rs) in the stdweb repo is under `webapi`, not `web`. Maybe that has something to do with it?

Or maybe it is because the [`Cargo.toml` for this project is referencing stdweb 0.4](https://github.com/ryanisaacg/quicksilver/blob/development/Cargo.toml#L46) which I'm pretty sure doesn't have `gamepad.rs` (looks like it was added in 0.4.7).

**Comment by ryanisaacg** [comment] 2018-06-27 21:39
- The web builds now go through [cargo web](https://github.com/koute/cargo-web) which is possibly the cause of your issue
- Possibly you also need to try running `cargo update`? It shouldn't be that, but it might be
- `webapi` is re-exported under `web` in stdweb, it shouldn't be an issue.
- Cargo uses semver for releases, which means that "0.4" will retrieve the newest 0.4.x version.
