### ISSUE TITLE
Cant run example

### ISSUE THREAD

**Issue by knipferrc** [ryanisaacg/quicksilver#169] opened 2018-04-05 16:37 UTC
Running the basic example on osx with the latest version of rust stable gives me the error: 
```
[rustc]
unresolved import `quicksilver::State`

no `State` in the root
```

Also, would this project be suitable to build on top of to build a simple text editor? I'm completely new to rust and looking to build a simple gui text editor.

**Comment by ryanisaacg** [comment] 2018-04-05 18:17
My I ask what command you used to compile and run the example?

**Comment by ryanisaacg** [comment] 2018-04-05 18:48
Oh, I figured out the problem. The version of quicksilver the example wants to use is `0.1.1`, which is the latest version on crates.io (not sure if you're familiar with it, it's the online repository for rust libraries.) The version in the master branch is in-progress, but it will be `0.2.0` when it is released. 

You can look at the sources for the [previous version](https://github.com/ryanisaacg/quicksilver/tree/v0.1.1) or point your Cargo at the master branch of quicksilver with:

```
[dependencies]
quicksilver = {git = "https://github.com/ryanisaacg/quicksilver" }
```

I would personally recommend the latter, as quicksilver has undergone many changes and I'm planning to release `0.20` sometime this month if all goes well.


As to whether quicksilver is a good fit, the docs all assume an intermediate knowledge of Rust and as of right now there is no convenient way to read text input. (The keyboard input in the library is much more geared to a game, ie checking if the player hits "D" rather than reading in the string they're currently typing.)

**Comment by knipferrc** [comment] 2018-04-05 19:01
Oh gotcha, thank you so much, ill test it out!

**Comment by ryanisaacg** [comment] 2018-04-05 22:26
Also, to satisfy my curiosity, may I ask how you found quicksilver?

**Comment by knipferrc** [comment] 2018-04-06 12:53
Of course, I was looking for a decent GUI lib that looked fairly easy to start off with since i'm just starting rust, and this looked like a good solution to that problem. After searching google for a while I came upon this repo.

**Comment by knipferrc** [comment] 2018-04-09 18:03
Im on OSX 10.13.3

**Comment by ryanisaacg** [comment] 2018-04-09 18:40
I'm also on macOS 10.13.3. If you have gdb, can you try running `gdb target/debug/ion` and posting the backtrace? (If you're unfamiliar with gdb, run the initial command then give gdb the command "r". It should still segfault; after that you can run the command "backtrace" in gdb and copy it)

**Comment by francesca64** [comment] 2018-06-10 17:02
If @knipferrc was running nightly, this was likely the result of tomaka/winit#426, at least judging by the timing.

(Also, AFAIK you're better off asking people on macOS to use `lldb` rather than `gdb`.)

**Comment by ryanisaacg** [comment] 2018-06-13 19:28
Good to know @francesca64 , considering I can't repro this and it's apparently caused by a now-fixed issue I'll close this until anyone else can reproduce.

**Closed by ryanisaacg** 2018-06-13 19:28 UTC
Labels: bug: needs repro, question
